name: Terraform Destroy

on:
  workflow_dispatch:


jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Plan Destroy
        run: terraform plan -destroy

      - name: Terraform  Destroy
        run: terraform destroy -auto-approve


